### PR TITLE
DomRenderer

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by kof** [comment]
@mpal9000 here you go

**Comment by kof** [comment]
DomRenderer could be a separate repository, but I don't wont overcomplicate it for now.

**Comment by kof** [comment]
@mpal9000 any thoughts on this one?

**Comment by kof** [comment]
now potentially someone can create a webgl renderer))))

**Comment by kof** [comment]
ping @mpal9000 )

**Comment by mpal9000** [comment]
I'll check tonight or tomorrow

**Comment by kof** [comment]
need to merge it now, because browserstack stuff is asking for a link and I need this changes to continue working on #114 

I will wait for your code review before release though.

**Comment by mpal9000** [comment]
Hi, at this stage I would like to run and play with the new changes. I'll check as soon as possible...

**Comment by kof** [comment]
hi @mpal9000 can you ping me via email oleg008@gmail.com or jitter?

**Pull request merged**
