### PR TITLE
Replace NO-BREAK SPACE character with normal space in source code

### PR DESCRIPTION
**Pull request by nkbt**
For some reason there are heaps of NO-BREAK SPACE characters in the source code

http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=%C2%A0&mode=char

### CODE REVIEW

**Comment by kof** [comment]
thanks, merged ... I would love to know when and why sublime does this.

**Comment by kof** [comment]
published

**Comment by nkbt** [comment]
That could be OSX rather then Sublime. And Sublime is not smart enough to un-fix this. OSX replaces a lot of things as-you-type, so this could be the case. IDEA/Webstorm do not have this issue as far as i know.

**Comment by nkbt** [comment]
http://superuser.com/questions/78245/how-to-disable-the-option-space-key-combination-for-non-breaking-spaces

> As mentioned in the comments, the solution provided by Martin does not work in some applications, most importantly (for me) in my editor, Sublime Text 2.

> So for all of you who are troubled by none breaking spaces in your code, you can add the following custom keybinding into your user keymap ("Sublime Text 2 > Preferences > Key Bindings - User"):
```
{ "keys": ["alt+space"], "command": "insert_snippet", "args": {"contents": " " } }
```
This will insert a regular space instead of a non-breaking one.

**Comment by kof** [comment]
wow thanks a lot!

**Comment by nkbt** [comment]
@kof check this: http://eslint.org/docs/rules/no-irregular-whitespace

**Comment by kof** [comment]
:+1:

**Pull request merged**
