### PR TITLE
Return the instance from jss.use()

### PR DESCRIPTION
**Pull request by mpal9000**

### CODE REVIEW

**Comment by kof** [comment]
do you really want it to look like this:

```
  jss.use(something)
     .use(something)  
     .use(something)
     .use(something)
```

vs.

```
  jss.use(something)
  jss.use(something)
  jss.use(something)
  jss.use(something)
```

I intentionally didn't return

**Comment by kof** [comment]
Also there is not much value in returning  something one have a reference to anyways.

**Comment by mpal9000** [comment]
I think that `use()` is a very common plugin related method and being chainable is something also very common. Probably it is the expected behaviour and also it's better to leave that style choice to the user. But in any way this is a very useful library and thank you!

**Comment by kof** [comment]
allright, lets allow them this fun)

**Comment by mpal9000** [comment]
These are also nice:
```javascript
jss.use(something).use(something).use(something).use(something)
```
```javascript
jss
.use(something)
.use(something)  
.use(something)
.use(something)
```
:smile:

**Comment by kof** [comment]
yeah, love them...

**Pull request merged**
