### PR TITLE
Add jss.version

### PR DESCRIPTION
**Pull request by watilde**
from https://github.com/jsstyles/jss/pull/211. This part we discussed before become simple and readable code. The benefit is the `jss.version` in `src/jss.js` can work fine without babel's transpile process.

```js
if (!global.__VERSION__) {
  global.__VERSION__ = require('../package.json').version
}
```

### CODE REVIEW

**Comment by kof** [comment]
Don't understand how this should work in the lib version generated by babel.

Also why do you need to use global ... you can just do typeof

**Comment by kof** [comment]
Oh I do understand now how this should work within babel, but this way you load the entire config and also use require. We use imports everywhere , require looks like  a hack.

**Comment by watilde** [comment]
The reason why I used `global.__VERSION__` is, webpack will build `dist/jss.js` and `dist/jss.min.js` as a file contains entire `package.json` config unfortunately if we use `typeof __VERSION__`.

It's really correct. Currently [test/Jss.js](https://github.com/jsstyles/jss/blob/master/test/Jss.js#L1) is depending on src files and it the complex point. If the test can use `lib/index.js` for test, we can make it simpler. Just it can be passed the version value from Babel plugin.
> We use imports everywhere , require looks like a hack.

**Comment by kof** [comment]
What if we just use something like this: https://github.com/gkz/grasp
No webpack variable, no babel plugins.
I didn't try it but it seems like we could do it very easily, take a look.

**Comment by watilde** [comment]
I updated this patch to make it simple again. Finally it worked fine with only webpack and babel. The only thing I should do is just use same name of the variable for version...

**Comment by kof** [comment]
Nice, this looks much better!

**Comment by kof** [comment]
merged!!!!

**Comment by kof** [comment]
thanks a lot!

**Comment by watilde** [comment]
Thank you so much for following up hardly! Cheers.

**Pull request merged**
